version: "3.9"
services:
  app:
    image: node:17.1.0-alpine3.13
    container_name: graphql-prisma-nexus-app
    volumes:
      - type: bind
        source: .
        target: /workspace
    working_dir: /workspace
    ports:
      - 4000:4000
    tty: true
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres@graphql-prisma-nexus-postgresql:5432/example
    command: npm start
  db:
    image: postgres:13.4-alpine3.14
    container_name: graphql-prisma-nexus-postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: example
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C.UTF-8"
      TZ: "Asia/Tokyo"
      LANG: "C.UTF-8"
    restart: always
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
